### ISSUE TITLE
Error: CertPathValidationExeption. Trust anchor for cert path not found [and suggest a definite requirement]

### ISSUE THREAD

**Issue by WillemsenGithub** [phpbg/easysync#28]
Error: 
When entering credentials
Error: CertPathValidationExeption. Trrust anchor for cert path not found

LineageOS 19
NC 28 Server, works like a charm

Guess issue is caused by a Custom Certificate. Maybe. The Readme here describes how to enter that in Android, but cant find it in LineageOS. 

Some Android apps simply ask you to accept a Custom cert, would be nice default functionality.

**Comment by WillemsenGithub** [comment]
Just hang in there, maybe found a workaround

**Comment by phpbg** [comment]
Your certificate common name should match the name you use to reach your server. Disabling a security measures defeats the purpose of TLS.

* If your server is public, just use your DNS record on your phone and have it in the CN of your certificate.
* Otherwise,
  * if you use an IP address, add it to your CN (or alt name),
  * if you use a local hostname resolution on your local network, add it to your CN (or alt name)

**Comment by WillemsenGithub** [comment]
The CN name matches the DNS name, of course. Only the port is different

All other Android apps (NC, Davx, TotCmd DavX, Browsers etc) have no issue with this, may ask confirmation, then I accept.
Its likely on the apps size of things.

**Comment by phpbg** [comment]
AFAIK the port is usually not checked when making TLS connection.

Does your CN include a port?

**Comment by WillemsenGithub** [comment]
No it does not, it says "host.domain.ext" [specific details left out] exactly as it is registered in Dynamic DNS
Additionally tried FolderSynch, also just asks for confirmation and does what it should (adds however, so skip)
Am I missing sth here ?

**Comment by phpbg** [comment]
See #39
