### ISSUE TITLE
Can't connect on local network

### ISSUE THREAD

**Issue by cacharle** [phpbg/easysync#6]
I have a photoprism instance on my local network I'd like to sync to with my phone.

When I try to connect to it with this client, I get the following error:

```
Error: CLEARTEXT communication to photoprism.home not permitted by network security policy
```

I do not have HTTPS setup for this instance.

I tried with another webdav client (on my desktop) and it worked.

**Comment by phpbg** [comment]
Hi, thanks for your report.

Indeed connecting over HTTP is forbidden *by android security policy* since android 9.

While I understand it complicates your home setup, it is an important security measure. When you connect over HTTP, all your data (including login/password) is transmitted in clear.

* If your photoprism instance is exposed over internet, I highly suggest you get proper HTTPS. For example you can use [Let's Encrypt](https://letsencrypt.org) with [Certbot](https://certbot.eff.org/instructions) which are free to use and easy to setup.
* If your photoprism instance is **not** exposed over internet, you can setup HTTPS with a self signed certificate. In that case you will have to make android trust your certificate, by adding it in android `Settings` > `Encryption and Credentials`

[Photoprism documentation](https://docs.photoprism.app/getting-started/#https) is a bit light on HTTPS setup. They suggest Traefik or Caddy, but i would personally use either apache, nginx or HAProxy...


NB: it seems photoprism [does not preserve file creation/modify timestamps](https://github.com/photoprism/photoprism/issues/3942) (but it reads them from exif image metadata). Please let me know if you manage to get it work...

**Comment by cacharle** [comment]
It's not exposed to the internet ofc 😄.

I'll try to get a certificate, thx.

**Comment by cacharle** [comment]
But I'm confused because I was able to connect to it with DAVx5 (davx5.com). How can it be an Android limitation if another app is able to connect to it?

**Comment by phpbg** [comment]
You can allow clear text at application level: https://developer.android.com/guide/topics/manifest/application-element#usesCleartextTraffic

DAVx5 did this by adding a [custom security policy](https://github.com/bitfireAT/davx5-ose/blob/dev-ose/app/src/main/res/xml/network_security_config.xml)

I find it dangerous, especially for mobile device that connects to many random networks...

**Comment by cacharle** [comment]
aah, I see, thank you

**Comment by stokito** [comment]
I'm using a local WebDAV server on a router and having the TLS really just adds problems. Maybe we can show a warning to a user for the plain HTTP urls?

**Comment by phpbg** [comment]
That could be a solution (showing a warning). I'll keep this open.

**Comment by stokito** [comment]
I do have a cert on my router from LetsEncrypt but it's expired. The EasySync just discards the cert without asking. This is probably a correct behavior but I beleive that even self signed certs won't be accepted.

**Comment by phpbg** [comment]
> I do have a cert on my router from LetsEncrypt but it's expired. The EasySync just discards the cert without asking. This is probably a correct behavior but I beleive that even self signed certs won't be accepted.

It is the correct behavior for an expired certificate. Self signed cert **should** work if you add it to android certificates store, but I havent tried yet...

**Comment by phpbg** [comment]
Hi @cacharle http is available with latest release.

Please either wait for v1.4 release on google playstore (within few hours), or [download the latest version here](https://github.com/phpbg/easysync/releases/tag/v1.4).

Can you report back if this works for you? (I am also intersted on a photoprism feedback...)

**Comment by cacharle** [comment]
will do :)

**Comment by cacharle** [comment]
Just tested it and it works as expected (allows it but shows a warning).
Thank you for your work

**Comment by cacharle** [comment]
Photoprism handles the folder structure without any problem.

It's just a bit annoying that my music and other unrelated files have been copied to my photoprism instance aswell :sweat_smile:. But I saw there is already an issue opened for that #3
